.github/workflows/nightly.yml, goreleaser.yaml
we were pushing just to ghcr before as well
=> fix: nightlies dont need docker hub login

goreleaser.yaml
nightly docker image tags have an extra `v` prefixed
=> fix: docker nightly tag name

.github/workflows/build.yml, .github/workflows/goreleaser.yml, .github/workflows/nightly.yml, .github/workflows/snapshot.yml
also made it possible to override the go version where the workflows are reused.
=> feat: update to go 1.18

goreleaser-full.yaml, goreleaser-semi.yaml, goreleaser.yaml
Skip publishing to fury.io when token is not set
=> fix: skip fury.io publish when env token doesn't exist

.github/workflows/goreleaser.yml
store gpg key in the parent directory, otherwise, goreleaser will error `git is currently in a dirty state`
=> fix: workaround goreleaser dirty git state

goreleaser-enterprise.yaml, goreleaser-full.yaml, goreleaser-semi.yaml, goreleaser.yaml
nightly and release docker image tags are inconsistent regarding version naming. releases add `v` prefix to the tag name, but nightly builds do not.
=> fix(goreleaser): add docker images "v" prefix

goreleaser-full.yaml, goreleaser-semi.yaml
they should be at `vendor_completions.d`: https://fishshell.com/docs/current/completions.html#where-to-put-completions
=> fix: fish completions path

goreleaser-full.yaml, goreleaser-lib.yaml, goreleaser-semi.yaml, goreleaser.yaml
Improves the changelog a bit:
- removes merge commits and other not-very-useful lines
- better organize the output, with a new dependencies and documentation categories
fwiw this is the same config I use for goreleaser/goreleaser - example: https://github.com/goreleaser/goreleaser/releases/tag/v1.10.0
let me know what you think :)
=> feat: improve changelogs

goreleaser-full.yaml, goreleaser-glow.yaml, goreleaser-semi.yaml, goreleaser-soft-serve.yaml, goreleaser-vhs.yaml, goreleaser.yaml
Adds a Scoop pipeline to publish Scoop app manifests.
Uses the same Homebrew variables since they're technically the same.
https://github.com/charmbracelet/scoop-bucket
=> feat: add scoop pipeline

.github/workflows/goreleaser.yml, goreleaser-annouce.yaml
I'm setting all the secrets at the org level, which should then work everywhere.
We can selectively enable the announce feature by including it in the projects we want to.
=> feat: announce using goreleaser

.github/workflows/goreleaser.yml
currently auth with 0.7 is not working properly... this will force use of 6.x, which should still work.
https://forum.snapcraft.io/t/craft-store-error-credentials-found-for-snapcraft-on-dashboard-snapcraft-io/33549
=> fix: force use snap 6.x until they fix their stuff

goreleaser-glow.yaml
refs https://github.com/charmbracelet/glow/issues/448
this will use the conventional file name for each format/arch as filename in the nfpm files.
an example of what it looks like: https://github.com/goreleaser/goreleaser/releases/tag/v1.14.1
=> fix: use conventional file names for nfpm packages

goreleaser-enterprise.yaml, goreleaser-full.yaml, goreleaser-glow.yaml, goreleaser-semi.yaml, goreleaser-soft-serve.yaml, goreleaser-vhs.yaml, goreleaser.yaml
new cosign versions need a `--yes` flag to auto-accept prompts, and don't need the experimental env anymore, as the features we used are no longer experimental :)
=> fix: signing for newer cosign versions

goreleaser-soft-serve.yaml
refs https://github.com/charmbracelet/scoop-bucket/pull/4
=> fix(soft-serve): bash is a not a scoop package

goreleaser-semi.yaml
Fixes: https://github.com/charmbracelet/charm/pull/258
=> fix: drop windows 386 from goreleaser-semi

goreleaser-full.yaml, goreleaser-glow.yaml, goreleaser-mods.yaml, goreleaser-semi.yaml, goreleaser-simple.yaml, goreleaser-soft-serve.yaml, goreleaser-vhs.yaml, goreleaser.yaml
https://github.com/charmbracelet/mods/issues/90
He's right, it would be frustrating for users to have files consistently
overwritten if they are using the archives to install from source. I changed
all archives to output to directories, feel free to change if it's overkill in
some of these cases.
https://goreleaser.com/customization/archive/?h=wrap_in
=> fix: extract to directory; no more tarbombs

goreleaser-enterprise.yaml, goreleaser-full.yaml, goreleaser-glow.yaml, goreleaser-lib.yaml, goreleaser-mods.yaml, goreleaser-semi.yaml, goreleaser-simple.yaml, goreleaser-soft-serve.yaml, goreleaser-vhs.yaml, goreleaser.yaml
This makes GoReleaser automatically detect prereleases based on the Git version tag.
=> feat: enable prerelease detection in goreleaser

.github/workflows/build.yml
`go install govulncheck` doesn't seem to work when built with Go 1.19, blocking https://github.com/charmbracelet/log/pull/141 for example.
It seems like there's no real benefit to running govulncheck for any non-stable Go version (correct me if I'm wrong).
I wasn't sure whether `go-version` or `go_version` were preferred, so I supported both.
=> ignore govulncheck for non-stable go version

.github/workflows/coverage.yml
This renames the workflow inputs to be more consistent with the rest of the workflows. And adds the ability to pass Codecov token.
=> feat(ci): update coverage workflow

.github/workflows/lint.yml, golangci-soft.yml, golangci.yml
This adds a shared workflow for linting Go code using golangci-lint. It adds golangci-lint configuration files for both the default and soft linting configurations and clones the meta repository to use the configuration files when running the workflow.
The golangci-lint configs were taken from bubbletea.
Repositories can then run the workflow using the following:
```yaml
name: lint
on:
push:
pull_request:
jobs:
lint:
uses: charmbracelet/meta/.github/workflows/lint.yml@main
```
=> feat(ci): add golangci-lint config and shared workflow

.github/workflows/lint-sync.yml
Automate copying the golangci-lint config from the meta repository to other repositories.
=> feat(ci): sync golangci-lint config workflow

.github/workflows/lint.yml, golangci-soft.yml
`typecheck` cannot be disabled because it's not linter, so the configuration is misleading because this has no effect.
- https://golangci-lint.run/welcome/faq/#why-is-it-not-possible-to-skipignore-typecheck-errors
- https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors
---
The action `actions/setup-go@v5` should be run after `actions/checkout@v4` for cache optimization.
=> fix(ci): lint configuration

.github/workflows/lint.yml
My PR #177 proves that the problem on Windows is not intermittent but consistent.
My initial guess was a problem with CRLF (Windows style) and I was right.
The problem is related to the `core.autocrlf`, by default, the GitHub Action on Windows uses `core.autocrlf=true`.
LF is converted to CRLF, and this produces file differences, so formatter like gofmt/gofumpt will report a problem.
Demo:
- The run fails: https://github.com/ldez/bubbletea/commit/b739658d6e0dd3dc849e251293725f48f62d55e1 https://github.com/ldez/bubbletea/actions/runs/11630127913
- The run works: https://github.com/ldez/bubbletea/commit/74a21c5f894c74b900afa1172f7a7b7d89252309  https://github.com/ldez/bubbletea/actions/runs/11630166096
Related to https://github.com/golangci/golangci-lint/issues/4004#issuecomment-2450731967
=> fix(lint): set core.autocrlf to input

README.md
Change README:
- goreleaser - GoReleaser
- gitHub actions -> GitHub Actions
=> docs: fix spelling for GoReleaser, GitHub in README

.github/workflows/lint.yml
The default timeout value of 1 minute is occasionally insufficient to complete the linting step in PRs.
https://github.com/charmbracelet/bubbletea/actions/runs/11873938591/job/33089318570?pr=1241#step:6:32
`msg="Timeout exceeded: try increasing it by passing --timeout option"`
=> Passing timeout arg to golangci-lint

goreleaser-enterprise.yaml, goreleaser-full.yaml, goreleaser-glow.yaml, goreleaser-lib.yaml, goreleaser-mods.yaml, goreleaser-semi.yaml, goreleaser-sequin.yaml, goreleaser-simple.yaml, goreleaser-soft-serve.yaml, goreleaser-vhs.yaml, goreleaser.yaml
We always edit the release title and description, so it is better to create the release as a draft and then we'll just mark as public once ready.
One real benefit of this is that people that watch our repositories receive an email about the release as soon as it becomes public, and this email will contain the actual title and description IIRC. By only publishing when ready, we ensure they receive our crafted description on their email, instead of the GoReleaser autogenerated description.
=> chore(goreleaser): create releases as draft

scripts/run-lint-sync.sh
[We have a similar script for Dependabot already.](https://github.com/charmbracelet/meta/blob/main/dependabot/run-workflow.sh)
=> feat: add script to run `lint-sync` for all repos

golangci.yml
Context: https://github.com/charmbracelet/glow/pull/735#discussion_r2027136655
We do have have `builtin` and `third_party` dirs, and I think we probably want to keep the `examples` dir in a good state, so removing them all.
=> chore(lint): do not exclude paths (added on conversion)

.github/dependabot.yml, dependabot/dependabot.yml
not sure why docker deps were getting the `feat` marker, lowered it to `chore` as the rest of the dep systems.
=> fix: consistent dependabot commits

golangci.yml
We commonly left TODOs in the code for the future, no reason to break the build over them.
See: https://golangci-lint.run/usage/linters/#godox
=> fix: do not throw lint errors on TODO

.github/workflows/lint.yml
Proposal for discussion. Avoid surprise lint failures in our repos.
Con is that we'll need to update this manually from time to time.
=> chore: use a fixed golangci-lint version and allow override

goreleaser-full.yaml, goreleaser-lib.yaml
This (hopefully) updates the headers to match the tone used in the release notes. I usually do this by hand every release in Crush, and often elsewhere.
=> chore: update changelog section header titles
