.github/workflows/goreleaser.yml
.github/workflows/snapshot.yml
goreleaser-full.yaml
goreleaser.yaml

this PR:
- adds aur support
- adds another goreleaser config which supports manpages and completions
- fix some template deprecations

feat: aur, completions, manpages, fix deprecations

---

.github/workflows/goreleaser.yml

fixes AUR key handling in the goreleaser action

fix: aur secret handling

---

goreleaser-full.yaml

Signed-off-by: Carlos A Becker <caarlos0@gmail.com>

fix: use license* instead of .md on aur

---

goreleaser-full.yaml

fix: license

---

goreleaser-full.yaml
goreleaser-semi.yaml
goreleaser.yaml

update goreleaser-semi to match goreleaser-full

feat: add fury.io integrations

---

.github/workflows/goreleaser.yml
goreleaser-full.yaml
goreleaser-semi.yaml
goreleaser.yaml

sign deb and rpm packages
in preparation to add gpg signing to https://repo.charm.sh/apt and https://repo.charm.sh/yum

feat(goreleaser): add nfpm deb/rpm package signing

---

goreleaser-full.yaml
goreleaser-semi.yaml

use /usr/share/zsh/site-functions instead of /usr/local/...

fix(goreleaser): nfpm zsh completion path

---

.github/workflows/build.yml
.github/workflows/goreleaser.yml
.github/workflows/nightly.yml
.github/workflows/snapshot.yml
goreleaser-glow.yaml

Specific Glow config with Snapcraft publishing.

feat: add glow goreleaser config

---

.github/workflows/build.yml
.github/workflows/goreleaser.yml
.github/workflows/nightly.yml
.github/workflows/snapshot.yml

- replace existing cache action with the setup-go action managed one
- added govulncheck job to the build workflow

feat: add govulncheck

---

templates/README.md

Link to our new Fediverse account and Discord chat in template footer.

docs: update template footer

---

templates/README.md

As discussed, let's keep it simple.

docs: clean up discord link

---

goreleaser-enterprise.yaml
goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-lib.yaml
goreleaser-semi.yaml
goreleaser-soft-serve.yaml
goreleaser.yaml

Signed-off-by: Carlos A Becker <caarlos0@users.noreply.github.com>

fix: change all slack links to discord

---

templates/README.md

Often fails displaying on Firefox & mobile Chrome.

docs: picture tag is causing display issues

---

.github/workflows/goreleaser.yml
goreleaser-enterprise.yaml
goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-lib.yaml
goreleaser-semi.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml
goreleaser.yaml

prevents yaml-language-server from complaining of "unknown property" because it auto-chooses the wrong schema based on the filename.

fix: added modelines where needed

---

.github/workflows/build.yml
.github/workflows/goreleaser.yml
.github/workflows/nightly.yml
.github/workflows/snapshot.yml

Always use the latest golang version available
Ref: https://github.com/actions/setup-go#check-latest-version

fix: check the latest golang version

---

.github/workflows/goreleaser.yml

secrets need to be passed...
refs #63

fix: secrets

---

goreleaser-glow.yaml

closes https://github.com/charmbracelet/glow/issues/445

fix: remove v prefix from glow --version

---

goreleaser-full.yaml
goreleaser-semi.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml
goreleaser.yaml

fix: use conventional file names in all nfpm pkgs

---

.github/workflows/govulncheck.yml
.github/workflows/ruleguard.yml
.github/workflows/semgrep.yml

based on https://github.com/caarlos0/meta with git config

feat: add govulncheck, ruleguard, and semgrep

---

.github/workflows/build.yml
.github/workflows/goreleaser.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly.yml
.github/workflows/ruleguard.yml
.github/workflows/semgrep.yml
.github/workflows/snapshot.yml

revert: the if changes

---

goreleaser-announce.yaml

fix: disable twitter announcements

---

goreleaser-soft-serve.yaml

- fix deprecation warns
- create service unit and etc config file
- post install/remove scripts

feat: soft-serve: package service, update config

---

goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-semi.yaml
goreleaser-simple.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml
goreleaser.yaml

Add version to package archives back
Format yaml using Prettier
Fixes: https://github.com/charmbracelet/vhs-action/issues/137
Fixes: ca2b089316d4 ("build: add a job to check all config files, and fix them all (#85)")

fix: include version in archives

---

goreleaser-enterprise.yaml
goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-semi.yaml
goreleaser-simple.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml
goreleaser.yaml

make goreleaser v1.19 happy :)

fix: lint issues

---

goreleaser-enterprise.yaml
goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-semi.yaml
goreleaser-simple.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml
goreleaser.yaml

feat: nix & winget

---

.github/workflows/goreleaser.yml
.github/workflows/nightly.yml

Download LFS files when `lfs` is true

feat: download lfs files

---

goreleaser-mods.yaml

update desc to match with the project desc

goreleaser-mods: update desc

---

goreleaser-full.yaml

feat: build for armv6

---

goreleaser-full.yaml

refs https://github.com/charmbracelet/scoop-bucket/pull/7

feat: allows to change the scoop.name

---

goreleaser-glow.yaml

closes https://github.com/charmbracelet/glow/issues/582

fix(glow): add removable-media plug to snap

---

goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-mods.yaml
goreleaser-semi.yaml
goreleaser-simple.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml

it's a good idea I think
refs https://aur.archlinux.org/packages/freeze-bin#comment-964671

feat: install readme to /usr/share/doc on aur

---

.github/workflows/snapshot.yml
goreleaser-enterprise.yaml
goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-mods.yaml
goreleaser-semi.yaml
goreleaser-simple.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml
goreleaser.yaml

fix: update configurations

---

.github/workflows/lint.yml

Related to https://github.com/charmbracelet/meta/pull/175#issuecomment-2445373434

chore(ci): remove only-new-issues option

---

goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-mods.yaml
goreleaser-semi.yaml
goreleaser-sequin.yaml
goreleaser-simple.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml
goreleaser.yaml

refs https://goreleaser.com/deprecations/#archivesformat_overridesformat

fix: deprecated options

---

golangci.yml

refs https://github.com/charmbracelet/meta/pull/200

feat: update config for golangci-lint v2

---

goreleaser-full.yaml
goreleaser-glow.yaml
goreleaser-mods.yaml
goreleaser-semi.yaml
goreleaser-sequin.yaml
goreleaser-simple.yaml
goreleaser-soft-serve.yaml
goreleaser-vhs.yaml
goreleaser.yaml

removes some repetition using https://goreleaser.com/customization/metadata/

refactor: use global metadata

---

.github/workflows/dependabot-sync.yml
.github/workflows/lint-sync.yml
.github/workflows/lint.yml

ci: fix lint action on forked repositories
